#!/command/with-contenv sh
. /run/signal-addon/options.env
if [ "${MODE}" != "json-rpc" ] && [ "${MODE}" != "json-rpc-native" ]; then
	exec sleep infinity
fi
exec s6-setuidgid signal-api jsonrpc2-helper
